#!/usr/bin/env bash
# ==============================================================================
# Create /opt/kailash/.env — the credentials docker compose interpolates.
#
# docker-compose.yml declares POSTGRES_PASSWORD, REDIS_PASSWORD and
# PLATFORM_INTERNAL_TOKEN with ${VAR:?...}, so every compose subcommand aborts
# during configuration parsing until this file exists. That is deliberate: the
# alternative was deploying on a password published in this repository.
#
# Compose reads .env from the directory containing docker-compose.yml. NOT
# backend/.env, which deploy.sh creates and which compose never consults for
# interpolation. Getting that wrong is the most likely way this step is done
# and still leaves the deploy failing.
#
# Usage:  bash deploy/vultr/bootstrap-env.sh [target-dir]
# ==============================================================================
set -euo pipefail

TARGET_DIR="${1:-/opt/kailash}"
ENV_FILE="${TARGET_DIR}/.env"

VARS=(POSTGRES_PASSWORD REDIS_PASSWORD PLATFORM_INTERNAL_TOKEN SECRET_KEY)

generate() {
    # 32 bytes of urandom, base64, url-safe. openssl is present on any host
    # that has already installed docker via get.docker.com.
    if command -v openssl &>/dev/null; then
        openssl rand -base64 32 | tr -d '\n=' | tr '+/' '-_'
    else
        head -c 32 /dev/urandom | base64 | tr -d '\n=' | tr '+/' '-_'
    fi
}

if [ ! -d "$TARGET_DIR" ]; then
    echo "✖ ${TARGET_DIR} does not exist" >&2
    exit 1
fi

if [ -f "$ENV_FILE" ]; then
    echo "✖ ${ENV_FILE} already exists. Refusing to overwrite." >&2
    echo "" >&2
    echo "  Overwriting would generate new credentials while the Postgres and" >&2
    echo "  Redis volumes still hold the old ones, so the stack would come up" >&2
    echo "  unable to authenticate against its own databases." >&2
    echo "" >&2
    echo "  To rotate deliberately, see rotate-credentials.sh." >&2
    exit 1
fi

umask 077
{
    echo "# Generated by deploy/vultr/bootstrap-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# Read by docker compose for \${VAR:?} interpolation. Never commit this file."
    for var in "${VARS[@]}"; do
        echo "${var}=$(generate)"
    done
    echo ""
    echo "# Required once ENV=production: app/core/config.py refuses to start on"
    echo "# the published default SECRET_KEY or on CORS_ORIGINS='*'."
    echo "ENV=dev"
    echo "CORS_ORIGINS=https://kailash-ai.in,https://www.kailash-ai.in,https://kailash-ai.com"
} > "$ENV_FILE"

chmod 600 "$ENV_FILE"

# Verify rather than assume. chmod is a no-op on some filesystems (a Windows
# checkout under Git Bash, a CIFS mount), and a world-readable credentials file
# is worth a loud warning rather than a silent success.
mode="$(stat -c '%a' "$ENV_FILE" 2>/dev/null || echo unknown)"
if [ "$mode" != "600" ] && [ "$mode" != "unknown" ]; then
    echo "⚠️  ${ENV_FILE} is mode ${mode}, not 600 — this filesystem ignored chmod." >&2
    echo "   Fix it before deploying: chmod 600 ${ENV_FILE}" >&2
fi

echo "✅ Wrote ${ENV_FILE} (mode ${mode}, $(wc -l < "$ENV_FILE") lines)"
echo ""
echo "Verify compose can now parse its configuration:"
echo "    cd ${TARGET_DIR} && docker compose config --quiet && echo OK"
echo ""
echo "Note: ENV is set to 'dev'. Switch it to 'production' only after"
echo "confirming SECRET_KEY and CORS_ORIGINS above are what you want —"
echo "startup fails loudly rather than silently accepting a bad value."
